name: IPTV

on:
    schedule:
      - cron: 0 0/12 * * * 
    workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date -u -d '+8 hour' '+%Y.%m.%d %H:%M:%S')"

    - name:  MY
      run: |   
        mkdir m3u
        wget https://raw.githubusercontent.com/gohkh0825/-TV-/refs/heads/main/m3u/my.m3u -O ./m3u/my.m3u
        sed -i '/#EXTM3U/d' ./m3u/my.m3u
        wget https://raw.githubusercontent.com/itszairi/FreeviewMY/refs/heads/main/FreelistenMY.m3u8 -O ./m3u/FreelistenMY.m3u8
        sed -i '/#EXTM3U/d' ./m3u/FreelistenMY.m3u8
        sed -i '/#################### FTA RADIO ####################/d' ./m3u/FreelistenMY.m3u8
        sed -i '/#################### END ####################/d' ./m3u/FreelistenMY.m3u8
         
    - name:  TEST
      run: |      
        wget https://raw.githubusercontent.com/alekchg/iptv/refs/heads/main/mysg.txt -O ./m3u/mysg.m3u8
        sed -i '/#EXTM3U/d' ./m3u/mysg.m3u8
        
    - name: JandaTV
      run: |      
        wget  http://tv.jnda.tech.gohkh7.eu.org/kbUjQ -O ./m3u/JandaTV.m3u8
        sed -i '/#EXTM3U/d' ./m3u/JandaTV.m3u8

    - name: allinone
      run: |      
        wget  https://allinone.gohkh9.us.kg/tv.m3u -O ./m3u/allinone-tv.m3u
        sed -i '/#EXTM3U/d' ./m3u/allinone-tv.m3u
        wget  https://allinone.gohkh9.us.kg/huyayqk.m3u -O ./m3u/allinone-huyayqk.m3u
        sed -i '/#EXTM3U/d' ./m3u/allinone-huyayqk.m3u
        wget  https://allinone.gohkh9.us.kg/bililive.m3u -O ./m3u/allinone-bililive.m3u
        sed -i '/#EXTM3U/d' ./m3u/allinone-bililive.m3u
        cat ./m3u//allinone-tv.m3u >> ./m3u/allinone.m3u
        cat ./m3u/allinone-huyayqk.m3u >> ./m3u/allinone.m3u
        cat ./m3u/allinone-bililive.m3u >> ./m3u/allinone.m3u
        rm -f ./m3u/allinone-tv.m3u
        rm -f ./m3u/allinone-huyayqk.m3u
        rm -f ./m3u/allinone-bililive.m3u
        
    
    - name: 节目源
      run: | 
       mkdir epg
       # astro_epg
        wget https://raw.githubusercontent.com/azimabid00/epg/main/astro_epg.xml -O ./epg/astro_epg.xml
       # FreeviewMY-EPG-1
        wget https://cutt.ly/FreeviewMY-EPG-1 -O ./epg/FreeviewMY-EPG-1
       # FreeviewMY-EPG-2
        wget https://cutt.ly/FreeviewMY-EPG-2 -O ./epg/FreeviewMY-EPG-2
       # aqfadtv
        wget https://aqfadtv.xyz/epg -O ./epg/aqfadtv
       # JandaTV
        wget http://tv.jnda.tech.gohkh7.eu.org/epg -O ./epg/JandaTV




    - name: 整合源
      run: |         
          # 整合源
           rm -f ./IPTV/IPTV.m3u && touch ./IPTV/IPTV.m3u
           cat ./m3u/JandaTV.m3u8 >> ./IPTV/IPTV.m3u
           cat ./m3u/mysg.m3u8 >> ./IPTV/IPTV.m3u
           cat ./m3u/my.m3u >> ./IPTV/IPTV.m3u
           cat ./m3u/FreelistenMY.m3u8 >> ./IPTV/IPTV.m3u
           cat ./m3u/allinone.m3u >> ./IPTV/IPTV.m3u
           rm  -rf IPTV/epg
           mkdir IPTV/epg
           cat ./epg/JandaTV >> ./IPTV/epg/epg-4.xml
           cat ./epg/aqfadtv >> ./IPTV/epg/epg-1.xml
           cat ./epg/FreeviewMY-EPG-2 >> ./IPTV/epg/epg-2.xml
           cat ./epg/FreeviewMY-EPG-1 >> ./IPTV/epg/epg-5.xml
           cat ./epg/astro_epg.xml >> ./IPTV/epg/epg-3.xml
           sed -i '/^\s*$/d' ./IPTV/IPTV.m3u
           sed -i '1i #EXTM3U x-tvg-url="https://gohkh0825.github.io/LIVE-TV/epg/epg-1.xml,https://gohkh0825.github.io/LIVE-TV/epg/epg-2.xml,https://gohkh0825.github.io/LIVE-TV/epg/epg-3.xml,https://gohkh0825.github.io/LIVE-TV/epg/epg-4.xml,https://gohkh0825.github.io/LIVE-TV/epg/epg-5.xml" refresh="24"' ./IPTV/IPTV.m3u
           echo "Auto Update IPTV in ${{ steps.date.outputs.date }}" > ./IPTV/README.md
           echo "Auto Update IPTV in ${{ steps.date.outputs.date }}" > README.md
           rm -f ./m3u/JandaTV.m3u8
           rm -f ./m3u/mysg.m3u8
           rm -f ./m3u/my.m3u
           rm -f ./m3u/allinone.m3u
           rm -f ./m3u/FreelistenMY.m3u8
           rm -f ./epg/astro_epg.xml
           rm -f ./epg/FreeviewMY-EPG-1
           rm -f ./epg/FreeviewMY-EPG-2
           rm -f ./epg/JandaTV
           rm -f ./epg/aqfadtv

    - name: Clean
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -a -m "Auto Update ${{ steps.date.outputs.date }}"

    - name: Push
      run: git push origin main
