name: IPTV

on:
    schedule:
      - cron: 0 0/12 * * * 
    workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date -u -d '+8 hour' '+%Y.%m.%d %H:%M:%S')"

    - name:  MY
      run: |       
        rm -f ./m3u/1/my.m3u && wget https://raw.githubusercontent.com/gohkh0825/LIVE-TV/refs/heads/main/m3u/my.m3u -O ./m3u/1/my.m3u
        sed -i '/#EXTM3U/d' ./m3u/1/my.m3u
        rm -f ./m3u/1/FreelistenMY.m3u8 && wget https://raw.githubusercontent.com/itszairi/FreeviewMY/refs/heads/main/FreelistenMY.m3u8 -O ./m3u/1/FreelistenMY.m3u8
        sed -i '/#EXTM3U/d' ./m3u/1/FreelistenMY.m3u8
        sed -i '/#################### FTA RADIO ####################/d' ./m3u/1/FreelistenMY.m3u8
        sed -i '/#################### END ####################/d' ./m3u/1/FreelistenMY.m3u8
         
    - name:  TEST
      run: |      
        rm -f ./m3u/1/mysg.m3u8 && wget https://raw.githubusercontent.com/alekchg/iptv/refs/heads/main/mysg.txt -O ./m3u/1/mysg.m3u8
        sed -i '/#EXTM3U/d' ./m3u/1/mysg.m3u8
        
    - name: JandaTV
      run: |      
        rm -f ./m3u/1/JandaTV.m3u8 && wget  https://webproxy.lumiproxy.com/sencure/Xl7RwOT82qQ4FwBqVAiBi -O ./m3u/1/JandaTV.m3u8
        sed -i '/#EXTM3U/d' ./m3u/1/JandaTV.m3u8
        
    
    - name: 节目源
      run: |        
       # astro_epg
        rm -f ./epg/astro_epg.xml && wget https://raw.githubusercontent.com/azimabid00/epg/main/astro_epg.xml -O ./epg/astro_epg.xml
       # FreeviewMY-EPG-1
        rm -f ./epg/FreeviewMY-EPG-1 && wget https://cutt.ly/FreeviewMY-EPG-1 -O ./epg/FreeviewMY-EPG-1
       # FreeviewMY-EPG-2
        rm -f ./epg/FreeviewMY-EPG-2 && wget https://cutt.ly/FreeviewMY-EPG-2 -O ./epg/FreeviewMY-EPG-2
       # aqfadtv
        rm -f ./epg/aqfadtv && wget https://aqfadtv.xyz/epg -O ./epg/aqfadtv
       # JandaTV
        rm -f ./epg/JandaTV && wget https://webproxy.lumiproxy.com/request?area=MY&u=https://tv.jnda.tech/epg -O ./epg/JandaTV




    - name: 整合源
      run: |         
          # 整合源
           rm -f ./IPTV/IPTV.m3u && touch ./IPTV/IPTV.m3u
           cat ./m3u/1/JandaTV.m3u8 >> ./IPTV/IPTV.m3u
           cat ./m3u/1/mysg.m3u8 >> ./IPTV/IPTV.m3u
           cat ./m3u/1/my.m3u >> ./IPTV/IPTV.m3u
           cat ./m3u/1/FreelistenMY.m3u8 >> ./IPTV/IPTV.m3u
           sed -i '/^\s*$/d' ./IPTV/IPTV.m3u
           sed -i '1i #EXTM3U x-tvg-url="https://gohkh0825.github.io/LIVE-TV/epg/astro_epg.xml,https://gohkh0825.github.io/LIVE-TV/epg/FreeviewMY-EPG-1,https://gohkh0825.github.io/LIVE-TV/epg/FreeviewMY-EPG-2,https://gohkh0825.github.io/LIVE-TV/epg/aqfadtv,https://gohkh0825.github.io/LIVE-TV/epg/JandaTV" refresh="24"' ./IPTV/IPTV.m3u
           echo "Auto Update IPTV in ${{ steps.date.outputs.date }}" > ./IPTV/README.md
           echo "Auto Update IPTV in ${{ steps.date.outputs.date }}" > README.md
       

    - name: Clean
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -a -m "${{ steps.date.outputs.date }}"

    - name: Push
      run: git push origin main
